### ISSUE TITLE
convert style strings to style objects

### ISSUE THREAD

**Issue by bmcmahen** [bmcmahen/create-react-icons#4]

**Comment by graysonhicks** [comment]
Getting this error when trying to import my Icons:

```Invariant Violation: The `style` prop expects a mapping from style properties to values, not a string. For example, style={{marginRight: spacing + 'em'}} when using JSX.```

Is that related?

**Comment by bmcmahen** [comment]
Yep, that's it. Not sure when I'll have the time to get to this, unfortunately. Would love a PR.

**Comment by bmcmahen** [comment]
Hey @graysonhicks , I recommend you use [svgr](https://www.smooth-code.com/open-source/svgr/docs/cli/) instead. It should support most of the features of this library but looks better supported and tested.
